Update URL instead of duplicating request on MultipleChoices status code
nuagenetworks/go-bambou pull request #11
Opened 2018-11-27 03:35 UTC by rvichery

Add unit test to check body passed to second request
Fixes #10

2018-11-27 16:55 UTC, rvichery commented
@pdellaert can you please review the changes

2018-11-27 17:28 UTC, pdellaert requested changes
Think the test can be expanded/improved a little.

Also curious to understand why the code didn't work in the first place... it is using the same request, and the body from that request. So why does the body remain the same in your code, but not in the original...

2018-11-27 17:28 UTC, pdellaert commented on bambou/session_test.go
> +					if requestBody.Test == "test" {
Shouldn't you also test that `responseChoice` is set to `1`?

2018-11-28 15:22 UTC, rvichery commented on bambou/session_test.go
> +					if requestBody.Test == "test" {
Yes. I added this in 0c14482

2018-11-28 15:55 UTC, pdellaert approved these changes

2018-11-28 15:56 UTC, merged